### ISSUE TITLE
Improve performance of XProcSpec

### ISSUE THREAD

**Issue by bertfrees** [daisy/xprocspec#41]
The reason why my unit tests are slow is partly because of XProcSpec. Now that the steps are producing info messages that has become quite clear. Let's take for example a module for which the tests take 12 minutes in total to complete. After 2 minutes the messages stop which suggests that XProcSpec is responsible for the remaining 10 minutes.

P.S.: Note that this could also be because of my custom compare steps, or the way the custom compare steps are invoked.
- [ ] I should try with the default comparator and with a custom mock comparator. I just looked at the x:pef-compare step and it contains a suspicious p:delete.

**Comment by josteinaj** [comment]
Ok. Yeah I really need to get around to updating xprocspec at some point; there's several annoying bugs.

Maybe it would make sense to drop using `cx:eval` as well and instead running each test separately from Java. The reason for using `cx:eval` is that you can pass an xprocspec file to calabash, and calabash will do the rest, instead of having to first compile, then run, then evaluate the results separately. However, I think it might be much more efficient (at least memory-wise) to run each step separately. I guess the way to do that would be first for me to refactor xprocspec a bit to be able to run each step separately (I don't think that's too much work), and then adapt xprocspec-maven-plugin a bit. I think you've suggested something similar earlier as well.

For performance there's probably several things that can be rewritten in XSLT as well.

**Comment by bertfrees** [comment]
See https://github.com/daisy/xprocspec/commit/cb772282b3b1f21e2eeeb2c987cc455eaf441317
